[mic]
type = 'rhasspy_junior.mic.CommandMicrophone'
max_queue_chunks = 100

    [mic.command]
    command = 'arecord -q -r 16000 -c 1 -f S16_LE -t raw'
    chunk_bytes = 2048
    stop_timeout_sec = 1

# -----------------------------------------------------------------------------

[hotword]
type = 'rhasspy_junior.hotword.PreciseHotword'

    [hotword.precise]
    model = "data/wake_precise/hey_mycroft.tflite"
    sensitivity = 0.8
    trigger_level = 4
    chunk_bytes = 2048

# -----------------------------------------------------------------------------

[vad]
type = 'rhasspy_junior.vad.SileroVoiceActivityDetector'

    [vad.silero]
    model = "data/vad_silero/silero_vad.onnx"
    threshold = 0.2
    sample_rate = 16000
    chunk_size = 960
    skip_seconds = 0
    min_seconds = 1
    max_seconds = 10
    speech_seconds = 0.3
    silence_seconds = 0.5
    before_seconds = 0.5

# -----------------------------------------------------------------------------

[stt]
type = 'rhasspy_junior.stt.FsticuffsSpeechToText'

    [stt.fsticuffs]
    model_dir = 'train/stt_fsticuffs'
    graph_dir = 'train/stt_fsticuffs/graph'
    sample_rate = 16000
    sample_width = 2
    channels = 1

    end_speech_timeout_sec = 5

    # platform is appended automatically
    kaldi_dir = 'data/stt_fsticuffs/kaldi'

# -----------------------------------------------------------------------------

[intent]
type = 'rhasspy_junior.intent.FsticuffsIntentRecognizer'

    [intent.fsticuffs]
    graph = 'train/intent_fsticuffs/graph.json'

# -----------------------------------------------------------------------------

[handle]
type = 'rhasspy_junior.handle.HomeAssistantIntentHandler'

     [handle.home_assistant]
     api_url = 'http://supervisor/core/api'
     api_token = ''
     intent_service_map = 'data/home_assistant/intent_service_map.toml'

        [handle.home_assistant.tts]
        service = 'tts/marytts_say'
        entities = { entity_id = 'media_player.vlc' }

# -----------------------------------------------------------------------------

[loop]
type = 'rhasspy_junior.loop.DefaultVoiceLoop'

    [loop.default]

# -----------------------------------------------------------------------------

[train]
type = 'rhasspy_junior.train.MultiTrainer'

    [train.multi]
    types = ['rhasspy_junior.train.HomeAssistantTrainer', 'rhasspy_junior.train.FsticuffsTrainer']

    [train.home_assistant]
    api_url = 'http://supervisor/core/api'
    api_token = ''
    input_template = 'data/home_assistant/sentences.template.ini'
    output_sentences = 'train/home_assistant/sentences.ini'

    [train.fsticuffs]
    force_retrain = false
    data_dir = 'data/stt_fsticuffs'
    train_dir = 'train/stt_fsticuffs'
    language = 'en-us'
    input_files = ['train/home_assistant/sentences.ini']
    output_skip_hash = 'train/intent_fsticuffs/skip_hash.txt'
    output_graph = 'train/intent_fsticuffs/graph.json'
    number_language = 'en'
    replace_numbers = true
    casing = 'lower'
